@url = http://localhost:8080/api

### - Should get all castaways

GET {{url}}/castaway/all HTTP/1.1
Content-Type: application/json

### - Should not get future season

GET {{url}}/castaway/season/69 HTTP/1.1
Content-Type: application/json

### - Should get castaway by season

GET {{url}}/castaway/season/42 HTTP/1.1
Content-Type: application/json