@url = http://localhost:8080/api
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmYW50YXN5LXN1cnZpdm9yIiwic3ViIjoiZGlhYmxvIiwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOLFJPTEVfTEVBR1VFX09XTkVSLFJPTEVfVVNFUiIsImFwcFVzZXJJZCI6MSwiZXhwIjoxNjYwMjQyNDg4fQ.nYqJGgeNnRfgyRUFv8WayGLjso4e-xhPIcUQPNg0SM4

### - Should get all castaways

GET {{url}}/castaway/all HTTP/1.1
Content-Type: application/json

### - Should get castaway by id

GET {{url}}/castaway/castaway19 HTTP/1.1
Content-Type: application/json


### - Should not get future season

GET {{url}}/castaway/season69 HTTP/1.1
Content-Type: application/json

### - Should get castaway by season

GET {{url}}/castaway/season42 HTTP/1.1
Content-Type: application/json

### - Should get castaway by tribal (no Marya or Jackson)

GET {{url}}/castaway/season42/tribal1 HTTP/1.1
Content-Type: application/json

### - Should Not get future tribal

GET {{url}}/castaway/season42/tribal100 HTTP/1.1
Content-Type: application/json

### - Should be able to get tribal number by season

GET {{url}}/castaway/tribals/season42 HTTP/1.1
Content-Type: application/json

### - Should not get invalid season

GET {{url}}/castaway/tribals/season43 HTTP/1.1
Content-Type: application/json

### - should post a castaway

POST {{url}}/castaway/new_castaway HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "Jeff",
    "lastName": "Probst",
    "age": 25,
    "currentResidence": "Fiji, always",
    "occupation": "Survivor",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/svr_cast_800x1000_0003_jeffprobst_0.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216299/"
}

### - should add castaway to season

POST {{url}}/castaway/season42/castaway20 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### - should remove castaway from season

DELETE  {{url}}/castaway/season42/castaway20 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### - should update a castaway

PUT {{url}}/castaway/change_castaway HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 19,
    "firstName": "Jeff",
    "lastName": "Probst",
    "age": 52,
    "currentResidence": "Fiji, always",
    "occupation": "Survivor",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/svr_cast_800x1000_0003_jeffprobst_0.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216299/"
}

### - should delete a castaway

DELETE {{url}}/castaway/castaway19 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 19,
    "firstName": "Jeff",
    "lastName": "Probst",
    "age": 52,
    "currentResidence": "Fiji, always",
    "occupation": "Survivor",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/svr_cast_800x1000_0003_jeffprobst_0.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216299/"
}


### - Post a tribal

POST {{url}}/castaway/season42/tribal3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "id": 1,
    "firstName": "Chanelle",
    "lastName": "Howell",
    "age": 29,
    "currentResidence": "Hamden, CT",
    "occupation": "Executive Recruiter",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_02_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216607/"
  },
  {
    "id": 2,
    "firstName": "Daniel",
    "lastName": "Strunk",
    "age": 30,
    "currentResidence": "New Haven, CT",
    "occupation": "Law Clerk",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_04_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216608/"
  },
  {
    "id": 3,
    "firstName": "Drea",
    "lastName": "Wheeler",
    "age": 35,
    "currentResidence": "Montreal, Quebec",
    "occupation": "Fitness Consultant",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_13_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216609/"
  },
  {
    "id": 4,
    "firstName": "Hai",
    "lastName": "Giang",
    "age": 29,
    "currentResidence": "New Orleans, LA",
    "occupation": "Data Scientist",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_05_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216610/"
  },
  {
    "id": 7,
    "firstName": "Jonathan",
    "lastName": "Young",
    "age": 29,
    "currentResidence": "Gulfshores, AL",
    "occupation": "Beach Service Co. Owner",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_12_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216613/"
  },
  {
    "id": 8,
    "firstName": "Lindsay",
    "lastName": "Dolashewich",
    "age": 31,
    "currentResidence": "Asbury Park, NJ",
    "occupation": "Dietitian",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_08_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216614/"
  },
  {
    "id": 9,
    "firstName": "Lydia",
    "lastName": "Meredith",
    "age": 22,
    "currentResidence": "Santa Monica, CA",
    "occupation": "Waitress",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_03_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216615/"
  },
  {
    "id": 11,
    "firstName": "Maryanne",
    "lastName": "Oketch",
    "age": 24,
    "currentResidence": "Ajax, Ontario",
    "occupation": "Seminary Student",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_09_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216617/"
  },
  {
    "id": 12,
    "firstName": "Mike",
    "lastName": "Turner",
    "age": 58,
    "currentResidence": "Hoboken, NJ",
    "occupation": "Retired Firefighter",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_06_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216618/"
  },
  {
    "id": 13,
    "firstName": "Omar",
    "lastName": "Zaheer",
    "age": 31,
    "currentResidence": "Whitby, Ontario",
    "occupation": "Veterinarian",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_11_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216619/"
  },
  {
    "id": 14,
    "firstName": "Rocksroy",
    "lastName": "Bailey",
    "age": 44,
    "currentResidence": "Las Vegas, NV",
    "occupation": "Stay at Home Dad",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_16_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216620/"
  },
  {
    "id": 15,
    "firstName": "Romeo",
    "lastName": "Escobar",
    "age": 37,
    "currentResidence": "Norwalk, CA",
    "occupation": "Pageant Coach",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_17_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216621/"
  },
  {
    "id": 17,
    "firstName": "Tori",
    "lastName": "Meehan",
    "age": 25,
    "currentResidence": "Tulsa, OK",
    "occupation": "Therapist",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_14_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216623/"
  }
]

### - Post a tribal

POST {{url}}/castaway/season42/tribal4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "id": 1,
    "firstName": "Chanelle",
    "lastName": "Howell",
    "age": 29,
    "currentResidence": "Hamden, CT",
    "occupation": "Executive Recruiter",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_02_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216607/"
  },
  {
    "id": 3,
    "firstName": "Drea",
    "lastName": "Wheeler",
    "age": 35,
    "currentResidence": "Montreal, Quebec",
    "occupation": "Fitness Consultant",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_13_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216609/"
  },
  {
    "id": 4,
    "firstName": "Hai",
    "lastName": "Giang",
    "age": 29,
    "currentResidence": "New Orleans, LA",
    "occupation": "Data Scientist",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_05_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216610/"
  },
  {
    "id": 7,
    "firstName": "Jonathan",
    "lastName": "Young",
    "age": 29,
    "currentResidence": "Gulfshores, AL",
    "occupation": "Beach Service Co. Owner",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_12_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216613/"
  },
  {
    "id": 8,
    "firstName": "Lindsay",
    "lastName": "Dolashewich",
    "age": 31,
    "currentResidence": "Asbury Park, NJ",
    "occupation": "Dietitian",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_08_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216614/"
  },
  {
    "id": 9,
    "firstName": "Lydia",
    "lastName": "Meredith",
    "age": 22,
    "currentResidence": "Santa Monica, CA",
    "occupation": "Waitress",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_03_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216615/"
  },
  {
    "id": 11,
    "firstName": "Maryanne",
    "lastName": "Oketch",
    "age": 24,
    "currentResidence": "Ajax, Ontario",
    "occupation": "Seminary Student",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_09_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216617/"
  },
  {
    "id": 12,
    "firstName": "Mike",
    "lastName": "Turner",
    "age": 58,
    "currentResidence": "Hoboken, NJ",
    "occupation": "Retired Firefighter",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_06_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216618/"
  },
  {
    "id": 13,
    "firstName": "Omar",
    "lastName": "Zaheer",
    "age": 31,
    "currentResidence": "Whitby, Ontario",
    "occupation": "Veterinarian",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_11_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216619/"
  },
  {
    "id": 14,
    "firstName": "Rocksroy",
    "lastName": "Bailey",
    "age": 44,
    "currentResidence": "Las Vegas, NV",
    "occupation": "Stay at Home Dad",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_16_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216620/"
  },
  {
    "id": 15,
    "firstName": "Romeo",
    "lastName": "Escobar",
    "age": 37,
    "currentResidence": "Norwalk, CA",
    "occupation": "Pageant Coach",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_17_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216621/"
  },
  {
    "id": 17,
    "firstName": "Tori",
    "lastName": "Meehan",
    "age": 25,
    "currentResidence": "Tulsa, OK",
    "occupation": "Therapist",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_14_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216623/"
  }
]

### - Delete a tribal

DELETE {{url}}/castaway/season42/tribal3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### - update a tribal

PUT {{url}}/castaway/season42/tribal3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "id": 2,
    "firstName": "Daniel",
    "lastName": "Strunk",
    "age": 30,
    "currentResidence": "New Haven, CT",
    "occupation": "Law Clerk",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_04_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216608/"
  },
  {
    "id": 3,
    "firstName": "Drea",
    "lastName": "Wheeler",
    "age": 35,
    "currentResidence": "Montreal, Quebec",
    "occupation": "Fitness Consultant",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_13_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216609/"
  },
  {
    "id": 4,
    "firstName": "Hai",
    "lastName": "Giang",
    "age": 29,
    "currentResidence": "New Orleans, LA",
    "occupation": "Data Scientist",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_05_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216610/"
  },
  {
    "id": 7,
    "firstName": "Jonathan",
    "lastName": "Young",
    "age": 29,
    "currentResidence": "Gulfshores, AL",
    "occupation": "Beach Service Co. Owner",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_12_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216613/"
  },
  {
    "id": 8,
    "firstName": "Lindsay",
    "lastName": "Dolashewich",
    "age": 31,
    "currentResidence": "Asbury Park, NJ",
    "occupation": "Dietitian",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_08_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216614/"
  },
  {
    "id": 9,
    "firstName": "Lydia",
    "lastName": "Meredith",
    "age": 22,
    "currentResidence": "Santa Monica, CA",
    "occupation": "Waitress",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_03_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216615/"
  },
  {
    "id": 11,
    "firstName": "Maryanne",
    "lastName": "Oketch",
    "age": 24,
    "currentResidence": "Ajax, Ontario",
    "occupation": "Seminary Student",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_09_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216617/"
  },
  {
    "id": 12,
    "firstName": "Mike",
    "lastName": "Turner",
    "age": 58,
    "currentResidence": "Hoboken, NJ",
    "occupation": "Retired Firefighter",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_06_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216618/"
  },
  {
    "id": 13,
    "firstName": "Omar",
    "lastName": "Zaheer",
    "age": 31,
    "currentResidence": "Whitby, Ontario",
    "occupation": "Veterinarian",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_11_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216619/"
  },
  {
    "id": 14,
    "firstName": "Rocksroy",
    "lastName": "Bailey",
    "age": 44,
    "currentResidence": "Las Vegas, NV",
    "occupation": "Stay at Home Dad",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_16_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216620/"
  },
  {
    "id": 15,
    "firstName": "Romeo",
    "lastName": "Escobar",
    "age": 37,
    "currentResidence": "Norwalk, CA",
    "occupation": "Pageant Coach",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_17_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216621/"
  },
  {
    "id": 17,
    "firstName": "Tori",
    "lastName": "Meehan",
    "age": 25,
    "currentResidence": "Tulsa, OK",
    "occupation": "Therapist",
    "iconURL": "https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w425-q80/cast/cbb_14_800x1000.jpg",
    "pageURL": "https://www.cbs.com/shows/survivor/cast/216623/"
  }
]
