@url = http://localhost:8080/api
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmYW50YXN5LXN1cnZpdm9yIiwic3ViIjoiZGlhYmxvIiwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOLFJPTEVfTEVBR1VFX09XTkVSLFJPTEVfVVNFUiIsImFwcFVzZXJJZCI6MSwiZXhwIjoxNjc3Mjk1OTQ0fQ.Acov8OV9dDOv2xhmzEPriJrZl7S16Dd3Y4kwfNXHTL0


POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "diablo",
    "password": "P@ssw0rd!"
}   

###

GET {{url}}/leaderboard/season42/league1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}