@url = http://localhost:8080/api
@admintoken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmYW50YXN5LXN1cnZpdm9yIiwic3ViIjoiZGlhYmxvIiwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOLFJPTEVfTEVBR1VFX09XTkVSLFJPTEVfVVNFUiIsImFwcFVzZXJJZCI6MSwiZXhwIjoxNjU5NTQwNDU4fQ.WBxCCztUof5A8NSGHRvFqK-rtxvRbNH1DM11rSieMYU
@usertoken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmYW50YXN5LXN1cnZpdm9yIiwic3ViIjoia2VubmVkeSIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiYXBwVXNlcklkIjo0LCJleHAiOjE2NTk1NDA2NjF9.UnCpBnduuW0FDgM0My0DQJwRQtMADNSJbJAzGMRfbZQ

### - admin can log in

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "diablo",
    "password": "P@ssw0rd!"
}   

### - user can log in

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "kennedy",
    "password": "P@ssw0rd!"
}

### - admin can get all

GET {{url}}/leagues/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admintoken}}

### - get league by Id should also return users in league

GET {{url}}/leagues/league1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admintoken}}

### - Should return none if not in league for user (400)

GET {{url}}/leagues/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admintoken}}

### - Should return leagues if in league (400)

GET {{url}}/leagues/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{usertoken}}